# run: conda env create -f environment.yml
# run: conda env update -f environment.yml
# run: conda env remove -n bioimg
name: bioimg
# in order of priority: lowest (top) to highest (bottom)
channels:
  - conda-forge
  - anaconda
dependencies:
  - click # adds nice cli features.
  - cython # wrapping Python around C. C is fast.
  - dask # parallelization
  - h5py # for the ubiquitous HDF5 file format. 
  - jupyter # great tool for any python project.
  - keras # deep learning library
  - pandas # working with tabulated data
  - pillow # classic fork of Python Imaging Library
  - pip # THE python package manager
  - python=3 # as of 2017, the latest python release
  - matplotlib # classic plotting
  - numpy # essential math and matrix operations
  - scikit-image # image processing
  - scikit-learn # machine learning
  - scipy # numerical methods
  - seaborn # plotting statistical data
  - sqlalchemy # working with SQL databases
  - tensorflow # deep learning backend for keras
  - tqdm # popular progress bar for jupyter
  - xlrd # Microsoft Excel
  - pip:
    - dash # Shiny is to R as Dash is to Python
    - dash-renderer
    - dash-html-components
    - dash-core-components
    - keras-tqdm # tqdm for keras
    - plotly  # fancy python plotting
    - tensorflow-gpu # deep learning on GPU hardware
