# run: conda env create -f environment.yml
# run: conda env update -f environment.yml
# run: conda env remove -n cellprofiler
name: cellprofiler
# in order of priority: lowest (top) to highest (bottom)
channels:
  - anaconda
  - goodman # mysql-python for mac
  - bioconda
  - cyclus # java-jdk for windows
  - conda-forge # libxml2 for windows
  - bjornfjohansson # wxpython 3.0.2.0
dependencies:
  - appdirs
  - boto3
  - cython
  - docutils
  - h5py
  - ipywidgets
  - javabridge
  - java-jdk
  - joblib
  - jupyter
  - libtiff
  - libxml2
  - libxslt
  - lxml
  - packaging
  - pillow
  - pip
  - python=2
  - pyzmq=15.3.0
  - mahotas
  - matplotlib>=2.0.0
  - mysql-python
  - numpy
  - raven
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - sphinx
  - tifffile
  - wxpython=3.0.2.0
  - pip:
    - cellh5
    - centrosome
    - inflect
    - prokaryote==2.3.3
    - python-bioformats==1.4.0
