# run: conda env create -f environment.yml
# run: conda env update -f environment.yml
# run: conda env remove -n dplrn
name: dplrn
# in order of priority: lowest (top) to highest (bottom)
channels:
  - conda-forge
  - anaconda
dependencies:
  - cython # wrapping Python around C. C is fast.
  - dask # parallelization
  - h5py # for the ubiquitous HDF5 file format. 
  - jupyter # great tool for any python project.
  - keras # deep learning library
  - pandas # working with tabulated data
  - pillow # classic fork of Python Imaging Library
  - pip # THE python package manager
  - python=3 # as of 2017, the latest python release
  - matplotlib # classic plotting
  - numpy # essential math and matrix operations
  - scikit-image # image processing
  - scikit-learn # machine learning
  - scipy # numerical methods
  - sqlalchemy # working with SQL databases
  - tensorflow # deep learning backend for keras
  - tqdm # popular progress bar for jupyter
  - pip:
    - keras-tqdm # tqdm for keras
    - tensorflow-gpu # deep learning on GPU hardware
