# run: conda env create -f environment.yml
# run: conda env update -f environment.yml
# run: conda env remove -n cellprofiler
name: bioimg
# in order of priority: lowest (top) to highest (bottom)
channels:
  - r
  - conda-forge
  - anaconda
dependencies:
  - click # adds nice cli features.
  - cython # wrapping Python around C. C is fast.
  - h5py # for the ubiquitous HDF5 file format. 
  - jupyter # great tool for any python project.
  - pandas # working with tabulated data
  - pillow # classic fork of Python Imaging Library
  - pip # THE python package manager
  - python=3 # as of 2017, the latest python release
  - matplotlib # classic plotting
  - numpy # essential math and matrix operations
  - r # stats!
  - r-dplyr # transform tabular data
  - r-essentials # gets R going
  - r-ggplot2 # beautiful plotting
  - r-magrittr # pipes
  - r-tidyr # makes dplyr better
  - rpy2 # python and r together
  - scikit-image # image processing
  - scikit-learn # machine learning
  - scipy # numerical methods
  - seaborn # plotting statistical data
  - sqlalchemy # working with SQL databases
  - xlrd # Microsoft Excel
  - pip:
    - wand # python interface to ImageMagick
    - dash # Shiny is to R as Dash is to Python
    - dash-renderer
    - dash-html-components
    - dash-core-components
    - plotly  # fancy python plotting
