# run: conda env create -f environment.yml
# run: conda env update -f environment.yml
# run: conda env remove -n cellprofiler
name: cp
# in order of priority: lowest (top) to highest (bottom)
channels:
  - anaconda
  - goodman # mysql-python for mac
  - bioconda
  - cyclus # java-jdk for windows
  - conda-forge # libxml2 for windows
dependencies:
  - appdirs
  - boto3
  - cython
  - h5py
  - ipywidgets
  - java-jdk
  - jupyter
  - libtiff
  - libxml2
  - libxslt
  - lxml
  - packaging
  - pillow
  - pip
  - python=2
  - pyzmq
  - mahotas
  - matplotlib
  - msgpack-python
  - mysql-python
  - numpy
  - raven
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - sphinx
  - tifffile
  - wxpython=3
  - pip:
    - cellh5
    - centrosome
    - inflect
    - javabridge
    - prokaryote
    - python-bioformats>=1.3.0
